apiVersion: v1
kind: Service
metadata:
  name: {{ include "poc8.fullname" . }}
  labels:
    {{- include "poc8.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: 
      protocol: TCP
      name: http
  selector:
    {{- include "poc8.selectorLabels" . | nindent 4 }}
